# Generated by Django 4.1.6 on 2023-02-12 22:09

from django.db import migrations


SITE_INITIAL_DATA = [
    ('CoinDesk', 'https://www.coindesk.com'),
    ('Decrypt', 'https://decrypt.co'),
    ('Cointelegraph', '	https://cointelegraph.com'),
    ('CryptoDaily', 'https://cryptodaily.co.uk'),
    ('U.Today', 'https://u.today'),
    ('CoinMarketCap', 'https://coinmarketcap.com/headlines/news'),
    ('DailyCoin', 'https://dailycoin.com'),
    ('CryptoNews', 'https://cryptonews.com'),
    ('BeInCrypto', 'https://beincrypto.com'),
]


def forward(apps, schema_editor):
    """
    Load initial data for the Site model.
    """
    Site = apps.get_model('data_labeling', 'Site')
    for name, url in SITE_INITIAL_DATA:
        Site.objects.create(name=name, url=url)


def backward(apps, schema_editor):
    """
    Rollback the previous data migration.
    """
    Site = apps.get_model('data_labeling', 'Site')
    for name, url in SITE_INITIAL_DATA:
        try:
            Site.objects.get(name=name, url=url).delete()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('data_labeling', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
