# Generated by Django 4.1.6 on 2023-02-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_labeling', '0002_auto_20230212_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
