# Generated by Django 4.1.6 on 2023-02-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
