# Generated by Django 4.1.6 on 2023-02-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0004_news_image_url_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
